chore: include new icons
tradersclub/TCIcons pull request #43
Opened 2021-04-05 14:56 UTC by TcTeamDesign

2021-04-05 23:18 UTC, arthurgeron-work requested changes

2021-04-05 23:18 UTC, arthurgeron-work commented on src/svg/alert-full.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M5.66671 23.986L13.932 9.03959C14.678 7.69048 16.6056 7.65712 17.3979 8.97962L26.2142 23.6961C27.0066 25.0188 26.0673 26.703 24.5254 26.7237L7.44384 2
É intencional a cor fixa destes ícones? Ou eles deveriam seguir o padrão de não ter uma cor "fill" definida para permitir que tenham suas cores alteradas?

2021-04-09 14:16 UTC, arthurgeron-work approved these changes

2021-04-09 17:29 UTC, PatrickChagastavares approved these changes

2021-04-09 17:29 UTC, merged